[16U7EMS1]
# GL65_Leopard_10SFSK                                                                                       
# 16U7EMS1.105
# max-cooling curve, 2026-08-10 (was: silence first; see fan-configs repo)                                                                                              
address_profile = MSI_ADDRESS_DEFAULT
fan_mode = 140
# CPU
cpu_temp_0 = 45
cpu_temp_1 = 52
cpu_temp_2 = 58
cpu_temp_3 = 64
cpu_temp_4 = 70
cpu_temp_5 = 76
cpu_fan_speed_0 = 35
cpu_fan_speed_1 = 50
cpu_fan_speed_2 = 60
cpu_fan_speed_3 = 70
cpu_fan_speed_4 = 85
cpu_fan_speed_5 = 95
cpu_fan_speed_6 = 100
# GPU
gpu_temp_0 = 50
gpu_temp_1 = 55
gpu_temp_2 = 60
gpu_temp_3 = 65
gpu_temp_4 = 70
gpu_temp_5 = 75
gpu_fan_speed_0 = 35
gpu_fan_speed_1 = 45
gpu_fan_speed_2 = 55
gpu_fan_speed_3 = 70
gpu_fan_speed_4 = 80
gpu_fan_speed_5 = 90
gpu_fan_speed_6 = 100
